(Dialog params_dialog
    (Components
        (SubLayout Content)
        (Separator CommitSeparator)
        (PushButton CommitOK)
        (PushButton CommitCancel)
    )
    (Resources
        (CommitSeparator.ResourceHints "Template:OKCancelDialog.CommitSeparator")
        (CommitOK.Label "Place")
        (CommitOK.TopOffset 10)
        (CommitOK.BottomOffset 10)
        (CommitOK.LeftOffset 40)
        (CommitOK.RightOffset 0)
        (CommitOK.ResourceHints "Template:OKCancelDialog.CommitOK" "UserOverrideAttrs:Label")
        (CommitCancel.Label "Cancel")
        (CommitCancel.TopOffset 10)
        (CommitCancel.BottomOffset 10)
        (CommitCancel.LeftOffset 8)
        (CommitCancel.RightOffset 10)
        (CommitCancel.ResourceHints "Template:OKCancelDialog.CommitCancel")
        (.TopOffset 0)
        (.BottomOffset 0)
        (.LeftOffset 0)
        (.RightOffset 0)
        (.DefaultButton "CommitOK")
        (.ResourceHints "Template:OKCancelDialog" "Guidelines:Creo4-Dialog" "GuidelinesVersion:2" "Version:Creo4" "@Subgrid0x2.Template:OKCancelDialog.CommitBar")
        (.Accelerator "Esc")
        (.Label "Parameters")
        (.AttachLeft True)
        (.Layout
            (Grid
                (Rows 1 0 0)
                (Cols 1)
                Content CommitSeparator
                (Grid
                    (Rows 1)
                    (Cols 1 0 0)
                    (Pos 1 2)
                    CommitOK
                    (Pos 1 3)
                    CommitCancel
                )
            )
        )
    )
)
(Layout Content
    (Components
        (Label Label1)
        (Separator Separator1)
        (SubLayout Layout1)
    )
    (Resources
        (Label1.Label "Bondpad Dimensions:")
        (Label1.AttachLeft True)
        (Label1.ResourceHints "UserOverrideAttrs:BottomOffset")
        (Label1.Alignment 0)
        (Label1.Resizeable True)
        (Label1.TopOffset 0)
        (Label1.BottomOffset 5)
        (Label1.LeftOffset 0)
        (Label1.RightOffset 0)
        (Separator1.TopOffset 6)
        (Separator1.BottomOffset 8)
        (.AttachLeft True)
        (.AttachRight True)
        (.AttachTop True)
        (.TopOffset 16)
        (.BottomOffset 16)
        (.LeftOffset 10)
        (.RightOffset 10)
        (.ResourceHints "Template:OKCancelDialog.Content")
        (.AttachBottom True)
        (.Layout
            (Grid
                (Rows 0 0 0)
                (Cols 1)
                Label1 Separator1 Layout1
            )
        )
    )
)
(Layout Layout1
    (Components
        (SubLayout label_layout)
        (SubLayout input_layout)
    )
    (Resources
        (.AttachLeft True)
        (.AttachRight True)
        (.AttachTop True)
        (.AttachBottom True)
        (.ResourceHints "UserOverrideAttrs:TopOffset")
        (.TopOffset 3)
        (.BottomOffset 0)
        (.LeftOffset 0)
        (.RightOffset 0)
        (.Layout
            (Grid
                (Rows 0)
                (Cols 0 1)
                label_layout input_layout
            )
        )
    )
)
(Layout label_layout
    (Components
        (Label Label1_copy1)
        (Label Label1_copy2)
    )
    (Resources
        (Label1_copy1.Label "Height:")
        (Label1_copy1.AttachLeft True)
        (Label1_copy1.ResourceHints "UserOverrideAttrs:TopOffset,BottomOffset")
        (Label1_copy1.Alignment 0)
        (Label1_copy1.Resizeable True)
        (Label1_copy1.TopOffset 10)
        (Label1_copy1.BottomOffset 10)
        (Label1_copy1.LeftOffset 0)
        (Label1_copy1.RightOffset 0)
        (Label1_copy2.Label "Width:")
        (Label1_copy2.AttachLeft True)
        (Label1_copy2.ResourceHints "UserOverrideAttrs:TopOffset,BottomOffset")
        (Label1_copy2.Alignment 0)
        (Label1_copy2.Resizeable True)
        (Label1_copy2.TopOffset 10)
        (Label1_copy2.BottomOffset 10)
        (Label1_copy2.LeftOffset 0)
        (Label1_copy2.RightOffset 0)
        (.AttachLeft True)
        (.AttachRight True)
        (.AttachTop True)
        (.AttachBottom True)
        (.ResourceHints "UserOverrideAttrs:RightOffset")
        (.TopOffset 0)
        (.BottomOffset 0)
        (.LeftOffset 0)
        (.RightOffset 3)
        (.Layout
            (Grid
                (Rows 0 0)
                (Cols 0)
                Label1_copy1 Label1_copy2
            )
        )
    )
)
(Layout input_layout
    (Components
        (InputPanel height_ip)
        (Label Label2_copy1)
        (InputPanel width_ip)
        (Label Label2_copy2)
    )
    (Resources
        (height_ip.Columns 5)
        (height_ip.ResourceHints "UserOverrideAttrs:LeftOffset")
        (height_ip.TopOffset 0)
        (height_ip.BottomOffset 3)
        (height_ip.LeftOffset 5)
        (height_ip.RightOffset 4)
        (height_ip.InputType 3)
        (height_ip.Digits 2)
        (Label2_copy1.Label "mm")
        (Label2_copy1.AttachLeft True)
        (Label2_copy1.Alignment 0)
        (Label2_copy1.Resizeable True)
        (Label2_copy1.TopOffset 0)
        (Label2_copy1.BottomOffset 3)
        (Label2_copy1.LeftOffset 3)
        (Label2_copy1.RightOffset 0)
        (width_ip.Columns 5)
        (width_ip.ResourceHints "UserOverrideAttrs:LeftOffset")
        (width_ip.TopOffset 3)
        (width_ip.BottomOffset 0)
        (width_ip.LeftOffset 5)
        (width_ip.RightOffset 4)
        (width_ip.InputType 3)
        (width_ip.Digits 2)
        (Label2_copy2.Label "mm")
        (Label2_copy2.AttachLeft True)
        (Label2_copy2.Alignment 0)
        (Label2_copy2.Resizeable True)
        (Label2_copy2.TopOffset 3)
        (Label2_copy2.BottomOffset 0)
        (Label2_copy2.LeftOffset 3)
        (Label2_copy2.RightOffset 0)
        (.AttachLeft True)
        (.AttachRight True)
        (.AttachTop True)
        (.AttachBottom True)
        (.ResourceHints "UserOverrideAttrs:LeftOffset")
        (.TopOffset 0)
        (.BottomOffset 0)
        (.LeftOffset 2)
        (.RightOffset 0)
        (.Layout
            (Grid
                (Rows 0 0)
                (Cols 1 0)
                height_ip Label2_copy1 width_ip Label2_copy2
            )
        )
    )
)
