(Dialog params_dialog
    (Components
        (SubLayout Content)
        (Separator CommitSeparator)
        (PushButton CommitOK)
        (PushButton CommitCancel)
    )
    (Resources
        (CommitSeparator.ResourceHints "Template:OKCancelDialog.CommitSeparator")
        (CommitOK.Label "Place")
        (CommitOK.TopOffset 10)
        (CommitOK.BottomOffset 10)
        (CommitOK.LeftOffset 40)
        (CommitOK.RightOffset 0)
        (CommitOK.ResourceHints "Template:OKCancelDialog.CommitOK" "UserOverrideAttrs:Label")
        (CommitCancel.Label "Cancel")
        (CommitCancel.TopOffset 10)
        (CommitCancel.BottomOffset 10)
        (CommitCancel.LeftOffset 8)
        (CommitCancel.RightOffset 10)
        (CommitCancel.ResourceHints "Template:OKCancelDialog.CommitCancel")
        (.TopOffset 0)
        (.BottomOffset 0)
        (.LeftOffset 0)
        (.RightOffset 0)
        (.DefaultButton "CommitOK")
        (.ResourceHints "Template:OKCancelDialog" "Guidelines:Creo4-Dialog" "GuidelinesVersion:2" "Version:Creo4" "@Subgrid0x2.Template:OKCancelDialog.CommitBar")
        (.Accelerator "Esc")
        (.Label "Parameters")
        (.AttachLeft True)
        (.Layout
            (Grid
                (Rows 1 0 0)
                (Cols 1)
                Content CommitSeparator
                (Grid
                    (Rows 1)
                    (Cols 1 0 0)
                    (Pos 1 2)
                    CommitOK
                    (Pos 1 3)
                    CommitCancel
                )
            )
        )
    )
)
(Layout Content
    (Components
        (SubLayout Layout1)
    )
    (Resources
        (.AttachLeft True)
        (.AttachRight True)
        (.AttachTop True)
        (.TopOffset 16)
        (.BottomOffset 16)
        (.LeftOffset 10)
        (.RightOffset 10)
        (.ResourceHints "Template:OKCancelDialog.Content")
        (.AttachBottom True)
        (.Layout
            (Grid
                (Rows 1)
                (Cols 1)
                Layout1
            )
        )
    )
)
(Layout Layout1
    (Components
        (SubLayout dimension_layout)
        (SubLayout fanout_attributes_layout)
        (SubLayout desc_layout)
    )
    (Resources
        (.AttachLeft True)
        (.AttachRight True)
        (.AttachTop True)
        (.AttachBottom True)
        (.ResourceHints "UserOverrideAttrs:TopOffset")
        (.TopOffset 3)
        (.BottomOffset 0)
        (.LeftOffset 0)
        (.RightOffset 0)
        (.Layout
            (Grid
                (Rows 0 0 1)
                (Cols 1)
                dimension_layout fanout_attributes_layout desc_layout
            )
        )
    )
)
(Layout dimension_layout
    (Components
        (Label height_lbl)
        (InputPanel height_ip)
        (Label height_units)
        (Label Label1_)
        (InputPanel width_ip)
        (Label width_units)
        (Label angle_lbl)
        (InputPanel angle_ip)
        (Label angle_units)
        (Label angle_lbl1)
    )
    (Resources
        (height_lbl.Label "Height:")
        (height_lbl.AttachLeft True)
        (height_lbl.ResourceHints "UserOverrideAttrs:TopOffset,BottomOffset")
        (height_lbl.Alignment 0)
        (height_lbl.Resizeable True)
        (height_lbl.TopOffset 10)
        (height_lbl.BottomOffset 10)
        (height_lbl.LeftOffset 7)
        (height_lbl.RightOffset 4)
        (height_ip.Columns 5)
        (height_ip.ResourceHints "UserOverrideAttrs:LeftOffset")
        (height_ip.TopOffset 6)
        (height_ip.BottomOffset 3)
        (height_ip.LeftOffset 40)
        (height_ip.RightOffset 4)
        (height_ip.InputType 3)
        (height_ip.Digits 2)
        (height_units.Label "micron")
        (height_units.AttachLeft True)
        (height_units.Alignment 0)
        (height_units.Resizeable True)
        (height_units.TopOffset 6)
        (height_units.BottomOffset 3)
        (height_units.LeftOffset 3)
        (height_units.RightOffset 7)
        (Label1_.Label "Width:")
        (Label1_.AttachLeft True)
        (Label1_.ResourceHints "UserOverrideAttrs:TopOffset,BottomOffset")
        (Label1_.Alignment 0)
        (Label1_.Resizeable True)
        (Label1_.TopOffset 10)
        (Label1_.BottomOffset 10)
        (Label1_.LeftOffset 7)
        (Label1_.RightOffset 4)
        (width_ip.Columns 5)
        (width_ip.ResourceHints "UserOverrideAttrs:LeftOffset")
        (width_ip.TopOffset 3)
        (width_ip.BottomOffset 3)
        (width_ip.LeftOffset 40)
        (width_ip.RightOffset 4)
        (width_ip.InputType 3)
        (width_ip.Digits 2)
        (width_units.Label "micron")
        (width_units.AttachLeft True)
        (width_units.Alignment 0)
        (width_units.Resizeable True)
        (width_units.TopOffset 3)
        (width_units.BottomOffset 3)
        (width_units.LeftOffset 3)
        (width_units.RightOffset 7)
        (angle_lbl.Label "Angle:")
        (angle_lbl.AttachLeft True)
        (angle_lbl.ResourceHints "UserOverrideAttrs:TopOffset,BottomOffset")
        (angle_lbl.Alignment 0)
        (angle_lbl.Resizeable True)
        (angle_lbl.TopOffset 10)
        (angle_lbl.BottomOffset 10)
        (angle_lbl.LeftOffset 7)
        (angle_lbl.RightOffset 4)
        (angle_ip.Columns 5)
        (angle_ip.ResourceHints "UserOverrideAttrs:LeftOffset")
        (angle_ip.TopOffset 3)
        (angle_ip.BottomOffset 2)
        (angle_ip.LeftOffset 40)
        (angle_ip.RightOffset 4)
        (angle_ip.InputType 3)
        (angle_ip.Digits 2)
        (angle_units.Label "micron")
        (angle_units.AttachLeft True)
        (angle_units.Alignment 0)
        (angle_units.Resizeable True)
        (angle_units.TopOffset 3)
        (angle_units.BottomOffset 2)
        (angle_units.LeftOffset 3)
        (angle_units.RightOffset 7)
        (angle_lbl1.Label "add (-) to reverse the 
angle direction")
        (angle_lbl1.ResourceHints "UserOverrideAttrs:LeftOffset,AttachLeft")
        (angle_lbl1.Alignment 0)
        (angle_lbl1.Resizeable True)
        (angle_lbl1.TopOffset 1)
        (angle_lbl1.BottomOffset 3)
        (angle_lbl1.LeftOffset 40)
        (angle_lbl1.RightOffset 4)
        (.AttachLeft True)
        (.AttachRight True)
        (.AttachTop True)
        (.AttachBottom True)
        (.ResourceHints "UserOverrideAttrs:RightOffset")
        (.TopOffset 0)
        (.BottomOffset 3)
        (.LeftOffset 0)
        (.RightOffset 3)
        (.Label "Dimensions")
        (.Decorated 1)
        (.Layout
            (Grid
                (Rows 0 0 0 0)
                (Cols 0 1 0)
                height_lbl height_ip height_units Label1_ width_ip width_units angle_lbl angle_ip angle_units
                (Pos 4 2)
                angle_lbl1
            )
        )
    )
)
(Layout fanout_attributes_layout
    (Components
        (Label offset_x_lbl)
        (InputPanel offset_x_ip)
        (Label offset_x_units)
        (Label offset_y_lbl)
        (InputPanel offset_y_ip)
        (Label offset_y_units)
        (Label trace_margin_lbl)
        (InputPanel trace_margin_ip)
        (Label trace_margin_units)
    )
    (Resources
        (offset_x_lbl.Label "Offset (X):")
        (offset_x_lbl.AttachLeft True)
        (offset_x_lbl.ResourceHints "UserOverrideAttrs:TopOffset,BottomOffset")
        (offset_x_lbl.Alignment 0)
        (offset_x_lbl.Resizeable True)
        (offset_x_lbl.TopOffset 10)
        (offset_x_lbl.BottomOffset 10)
        (offset_x_lbl.LeftOffset 7)
        (offset_x_lbl.RightOffset 4)
        (offset_x_ip.Columns 5)
        (offset_x_ip.ResourceHints "UserOverrideAttrs:LeftOffset")
        (offset_x_ip.TopOffset 6)
        (offset_x_ip.BottomOffset 3)
        (offset_x_ip.LeftOffset 5)
        (offset_x_ip.RightOffset 4)
        (offset_x_ip.InputType 3)
        (offset_x_ip.Digits 2)
        (offset_x_units.Label "micron")
        (offset_x_units.AttachLeft True)
        (offset_x_units.Alignment 0)
        (offset_x_units.Resizeable True)
        (offset_x_units.TopOffset 6)
        (offset_x_units.BottomOffset 3)
        (offset_x_units.LeftOffset 3)
        (offset_x_units.RightOffset 7)
        (offset_y_lbl.Label "Offset (Y):")
        (offset_y_lbl.AttachLeft True)
        (offset_y_lbl.ResourceHints "UserOverrideAttrs:TopOffset,BottomOffset")
        (offset_y_lbl.Alignment 0)
        (offset_y_lbl.Resizeable True)
        (offset_y_lbl.TopOffset 10)
        (offset_y_lbl.BottomOffset 10)
        (offset_y_lbl.LeftOffset 7)
        (offset_y_lbl.RightOffset 4)
        (offset_y_ip.Columns 5)
        (offset_y_ip.ResourceHints "UserOverrideAttrs:LeftOffset")
        (offset_y_ip.TopOffset 3)
        (offset_y_ip.BottomOffset 3)
        (offset_y_ip.LeftOffset 5)
        (offset_y_ip.RightOffset 4)
        (offset_y_ip.InputType 3)
        (offset_y_ip.Digits 2)
        (offset_y_units.Label "micron")
        (offset_y_units.AttachLeft True)
        (offset_y_units.Alignment 0)
        (offset_y_units.Resizeable True)
        (offset_y_units.TopOffset 3)
        (offset_y_units.BottomOffset 3)
        (offset_y_units.LeftOffset 3)
        (offset_y_units.RightOffset 7)
        (trace_margin_lbl.Label "Trace Margin:")
        (trace_margin_lbl.AttachLeft True)
        (trace_margin_lbl.ResourceHints "UserOverrideAttrs:TopOffset,BottomOffset")
        (trace_margin_lbl.Alignment 0)
        (trace_margin_lbl.Resizeable True)
        (trace_margin_lbl.TopOffset 5)
        (trace_margin_lbl.BottomOffset 3)
        (trace_margin_lbl.LeftOffset 7)
        (trace_margin_lbl.RightOffset 4)
        (trace_margin_ip.Columns 5)
        (trace_margin_ip.ResourceHints "UserOverrideAttrs:TopOffset,LeftOffset")
        (trace_margin_ip.TopOffset 5)
        (trace_margin_ip.BottomOffset 6)
        (trace_margin_ip.LeftOffset 5)
        (trace_margin_ip.RightOffset 4)
        (trace_margin_ip.InputType 3)
        (trace_margin_ip.Digits 2)
        (trace_margin_units.Label "micron")
        (trace_margin_units.AttachLeft True)
        (trace_margin_units.Alignment 0)
        (trace_margin_units.Resizeable True)
        (trace_margin_units.TopOffset 3)
        (trace_margin_units.BottomOffset 6)
        (trace_margin_units.LeftOffset 3)
        (trace_margin_units.RightOffset 7)
        (.Decorated 1)
        (.AttachLeft True)
        (.AttachRight True)
        (.AttachTop True)
        (.AttachBottom True)
        (.TopOffset 3)
        (.BottomOffset 3)
        (.LeftOffset 0)
        (.RightOffset 0)
        (.Label "Fanout attributes")
        (.Layout
            (Grid
                (Rows 0 0 0)
                (Cols 0 1 0)
                offset_x_lbl offset_x_ip offset_x_units offset_y_lbl offset_y_ip offset_y_units trace_margin_lbl trace_margin_ip trace_margin_units
            )
        )
    )
)
(Layout desc_layout
    (Components
        (Label Label1)
        (TextArea desc_textarea)
    )
    (Resources
        (Label1.Label "Note")
        (Label1.AttachLeft True)
        (Label1.AttachTop True)
        (Label1.Alignment 0)
        (Label1.Resizeable True)
        (Label1.TopOffset 6)
        (Label1.BottomOffset 6)
        (Label1.LeftOffset 7)
        (Label1.RightOffset 4)
        (desc_textarea.Wrap True)
        (desc_textarea.TopOffset 6)
        (desc_textarea.BottomOffset 6)
        (desc_textarea.LeftOffset 3)
        (desc_textarea.RightOffset 7)
        (desc_textarea.ScrollBarsWhenNeeded True)
        (.Decorated 1)
        (.AttachLeft True)
        (.AttachRight True)
        (.AttachTop True)
        (.AttachBottom True)
        (.TopOffset 3)
        (.BottomOffset 0)
        (.LeftOffset 0)
        (.RightOffset 0)
        (.Layout
            (Grid
                (Rows 1)
                (Cols 0 1)
                Label1 desc_textarea
            )
        )
    )
)
