(Dialog place_templates
    (Components
        (SubLayout Content)
        (Separator CommitSeparator)
        (PushButton CommitOK)
        (PushButton CommitCancel)
    )
    (Resources
        (CommitSeparator.ResourceHints "Template:OKCancelDialog.CommitSeparator")
        (CommitOK.Label "Place")
        (CommitOK.TopOffset 10)
        (CommitOK.BottomOffset 10)
        (CommitOK.LeftOffset 40)
        (CommitOK.RightOffset 0)
        (CommitOK.ResourceHints "Template:OKCancelDialog.CommitOK" "UserOverrideAttrs:Label")
        (CommitOK.Visible False)
        (CommitCancel.Label "Close")
        (CommitCancel.TopOffset 10)
        (CommitCancel.BottomOffset 10)
        (CommitCancel.LeftOffset 8)
        (CommitCancel.RightOffset 10)
        (CommitCancel.ResourceHints "Template:OKCancelDialog.CommitCancel" "UserOverrideAttrs:Label")
        (.TopOffset 0)
        (.BottomOffset 0)
        (.LeftOffset 0)
        (.RightOffset 0)
        (.DefaultButton "CommitOK")
        (.ResourceHints "Template:OKCancelDialog" "Guidelines:Creo4-Dialog" "GuidelinesVersion:2" "Version:Creo4" "@Subgrid0x2.Template:OKCancelDialog.CommitBar")
        (.Accelerator "Esc")
        (.AttachLeft True)
        (.Label "3D Printing")
        (.Columns 20)
        (.StartLocation 3)
        (.Gravity 3)
        (.Layout
            (Grid
                (Rows 1 0 0)
                (Cols 1)
                Content CommitSeparator
                (Grid
                    (Rows 1)
                    (Cols 1 0 0)
                    (Pos 1 2)
                    CommitOK
                    (Pos 1 3)
                    CommitCancel
                )
            )
        )
    )
)
(Layout Content
    (Components
        (Tab Tab1 template_layout functions_layout)
    )
    (Resources
        (Tab1.Decorated 1)
        (Tab1.TopOffset 0)
        (Tab1.BottomOffset 0)
        (Tab1.LeftOffset 0)
        (Tab1.RightOffset 0)
        (.AttachLeft True)
        (.AttachRight True)
        (.AttachTop True)
        (.TopOffset 16)
        (.BottomOffset 16)
        (.LeftOffset 10)
        (.RightOffset 10)
        (.ResourceHints "Template:OKCancelDialog.Content")
        (.AttachBottom True)
        (.Layout
            (Grid
                (Rows 1)
                (Cols 1)
                Tab1
            )
        )
    )
)
(Layout template_layout
    (Components
        (SubLayout buttons_layout)
    )
    (Resources
        (.Label "Templates")
        (.TopOffset 0)
        (.BottomOffset 0)
        (.LeftOffset 0)
        (.RightOffset 0)
        (.Layout
            (Grid
                (Rows 0)
                (Cols 0)
                buttons_layout
            )
        )
    )
)
(Layout buttons_layout
    (Components
        (PushButton pb_1)
        (PushButton pb_2)
    )
    (Resources
        (pb_1.Bitmap "bondpad.png")
        (pb_1.AttachLeft True)
        (pb_1.Resizeable True)
        (pb_1.TopOffset 0)
        (pb_1.BottomOffset 0)
        (pb_1.LeftOffset 0)
        (pb_1.RightOffset 4)
        (pb_1.ButtonAlignment 5531)
        (pb_1.Label "Bondpad")
        (pb_1.BackgroundColor 10)
        (pb_2.Bitmap "question.png")
        (pb_2.AttachLeft True)
        (pb_2.Resizeable True)
        (pb_2.TopOffset 0)
        (pb_2.BottomOffset 0)
        (pb_2.LeftOffset 3)
        (pb_2.RightOffset 0)
        (pb_2.ButtonAlignment 5531)
        (pb_2.Label "Bondpad")
        (.AttachLeft True)
        (.AttachRight True)
        (.AttachTop True)
        (.AttachBottom True)
        (.TopOffset 13)
        (.BottomOffset 13)
        (.LeftOffset 10)
        (.RightOffset 10)
        (.Layout
            (Grid
                (Rows 0)
                (Cols 0 0)
                pb_1 pb_2
            )
        )
    )
)
(Layout functions_layout
    (Components
        (SubLayout Layout3)
    )
    (Resources
        (.Label "Functions")
        (.TopOffset 0)
        (.BottomOffset 0)
        (.LeftOffset 0)
        (.RightOffset 0)
        (.Layout
            (Grid
                (Rows 0)
                (Cols 0)
                Layout3
            )
        )
    )
)
(Layout Layout3
    (Components
        (PushButton fanout_pb)
        (PushButton PushButton1_copy1)
        (PushButton PushButton1_copy2)
        (PushButton PushButton1_copy3)
    )
    (Resources
        (fanout_pb.AttachLeft True)
        (fanout_pb.Resizeable True)
        (fanout_pb.TopOffset 0)
        (fanout_pb.BottomOffset 3)
        (fanout_pb.LeftOffset 0)
        (fanout_pb.RightOffset 4)
        (fanout_pb.ButtonAlignment 5531)
        (fanout_pb.Label "Fanout")
        (fanout_pb.Columns 7)
        (fanout_pb.Bitmap "fanout.png")
        (PushButton1_copy1.AttachLeft True)
        (PushButton1_copy1.Resizeable True)
        (PushButton1_copy1.TopOffset 0)
        (PushButton1_copy1.BottomOffset 3)
        (PushButton1_copy1.LeftOffset 3)
        (PushButton1_copy1.RightOffset 4)
        (PushButton1_copy1.ButtonAlignment 5531)
        (PushButton1_copy1.Label "Pattern")
        (PushButton1_copy1.Columns 7)
        (PushButton1_copy1.Bitmap "question.png")
        (PushButton1_copy2.AttachLeft True)
        (PushButton1_copy2.Resizeable True)
        (PushButton1_copy2.TopOffset 0)
        (PushButton1_copy2.BottomOffset 3)
        (PushButton1_copy2.LeftOffset 3)
        (PushButton1_copy2.RightOffset 0)
        (PushButton1_copy2.ButtonAlignment 5531)
        (PushButton1_copy2.Label "Mirror")
        (PushButton1_copy2.Columns 7)
        (PushButton1_copy2.Bitmap "question.png")
        (PushButton1_copy3.AttachLeft True)
        (PushButton1_copy3.Resizeable True)
        (PushButton1_copy3.TopOffset 3)
        (PushButton1_copy3.BottomOffset 0)
        (PushButton1_copy3.LeftOffset 0)
        (PushButton1_copy3.RightOffset 4)
        (PushButton1_copy3.ButtonAlignment 5531)
        (PushButton1_copy3.Label "Clearance")
        (PushButton1_copy3.Columns 7)
        (PushButton1_copy3.Bitmap "question.png")
        (.AttachLeft True)
        (.AttachRight True)
        (.AttachTop True)
        (.AttachBottom True)
        (.TopOffset 13)
        (.BottomOffset 13)
        (.LeftOffset 10)
        (.RightOffset 10)
        (.Layout
            (Grid
                (Rows 0 0)
                (Cols 0 0 0)
                fanout_pb PushButton1_copy1 PushButton1_copy2 PushButton1_copy3
            )
        )
    )
)
