(Dialog 3DPRINTER
    (Components
        (SubLayout Content)
        (Separator CommitSeparator)
        (PushButton btnPreview)
        (PushButton btnOK)
        (PushButton btnCancel)
    )
    (Resources
        (CommitSeparator.ResourceHints "Template:OKCancelPreviewDialog.CommitSeparator")
        (btnPreview.Label "&Preview")
        (btnPreview.TopOffset 10)
        (btnPreview.BottomOffset 10)
        (btnPreview.LeftOffset 10)
        (btnPreview.RightOffset 0)
        (btnPreview.ResourceHints "Template:OKCancelPreviewDialog.CommitPreview")
        (btnPreview.Visible False)
        (btnPreview.Sensitive False)
        (btnOK.Label "OK")
        (btnOK.TopOffset 10)
        (btnOK.BottomOffset 10)
        (btnOK.LeftOffset 40)
        (btnOK.RightOffset 0)
        (btnOK.ResourceHints "Template:OKCancelPreviewDialog.CommitOK")
        (btnOK.Cursor "UI link cursor image")
        (btnCancel.Label "Cancel")
        (btnCancel.TopOffset 10)
        (btnCancel.BottomOffset 10)
        (btnCancel.LeftOffset 8)
        (btnCancel.RightOffset 10)
        (btnCancel.ResourceHints "Template:OKCancelPreviewDialog.CommitCancel")
        (btnCancel.Cursor "UI link cursor image")
        (.TopOffset 0)
        (.BottomOffset 0)
        (.LeftOffset 0)
        (.RightOffset 0)
        (.DefaultButton "btnOK")
        (.ResourceHints "Template:OKCancelPreviewDialog" "Guidelines:Creo4-Dialog" "GuidelinesVersion:2" "Version:Creo4" "@Subgrid0x2.Template:OKCancelPreviewDialog.CommitBar")
        (.Accelerator "Esc")
        (.Label "3D Printer")
        (.AttachLeft True)
        (.Resizeable False)
        (.Layout
            (Grid
                (Rows 1 0 0)
                (Cols 1)
                Content CommitSeparator
                (Grid
                    (Rows 1)
                    (Cols 0 1 0 0)
                    btnPreview
                    (Pos 1 3)
                    btnOK
                    (Pos 1 4)
                    btnCancel
                )
            )
        )
    )
)
(Layout Content
    (Components
        (PushButton PushButton1)
        (PushButton PushButton2)
        (PushButton PushButton3)
        (PushButton PushButton4)
        (PushButton PushButton5)
        (RadioGroup capacitorRadio1)
        (PushButton capacitorUpdate)
    )
    (Resources
        (PushButton1.Columns 5)
        (PushButton1.AttachLeft True)
        (PushButton1.Resizeable True)
        (PushButton1.TopOffset 6)
        (PushButton1.BottomOffset 3)
        (PushButton1.LeftOffset 5)
        (PushButton1.RightOffset 1)
        (PushButton1.ResourceHints "UserOverrideAttrs:LeftOffset,RightOffset")
        (PushButton2.Columns 5)
        (PushButton2.AttachLeft True)
        (PushButton2.Resizeable True)
        (PushButton2.TopOffset 6)
        (PushButton2.BottomOffset 3)
        (PushButton2.LeftOffset 5)
        (PushButton2.RightOffset 0)
        (PushButton2.ResourceHints "UserOverrideAttrs:AttachLeft,LeftOffset,RightOffset")
        (PushButton3.Columns 5)
        (PushButton3.AttachLeft True)
        (PushButton3.Resizeable True)
        (PushButton3.TopOffset 6)
        (PushButton3.BottomOffset 3)
        (PushButton3.LeftOffset 5)
        (PushButton3.RightOffset 7)
        (PushButton3.ResourceHints "UserOverrideAttrs:LeftOffset")
        (PushButton4.Columns 5)
        (PushButton4.AttachLeft True)
        (PushButton4.Resizeable True)
        (PushButton4.TopOffset 3)
        (PushButton4.BottomOffset 6)
        (PushButton4.LeftOffset 5)
        (PushButton4.RightOffset 0)
        (PushButton4.ResourceHints "UserOverrideAttrs:LeftOffset,RightOffset")
        (PushButton5.Columns 5)
        (PushButton5.AttachLeft True)
        (PushButton5.Resizeable True)
        (PushButton5.TopOffset 3)
        (PushButton5.BottomOffset 6)
        (PushButton5.LeftOffset 5)
        (PushButton5.RightOffset 5)
        (PushButton5.ResourceHints "UserOverrideAttrs:LeftOffset,RightOffset")
        (capacitorRadio1.Orientation True)
        (capacitorRadio1.HelpText "Capacitor")
        (capacitorRadio1.AttachRight False)
        (capacitorRadio1.AttachTop False)
        (capacitorRadio1.AttachBottom False)
        (capacitorRadio1.Resizeable True)
        (capacitorRadio1.TopOffset 6)
        (capacitorRadio1.BottomOffset 3)
        (capacitorRadio1.LeftOffset 5)
        (capacitorRadio1.RightOffset 10)
        (capacitorRadio1.Cursor "UI link cursor image")
        (capacitorRadio1.Names "capacitor" "antenna")
        (capacitorRadio1.Labels "Capacitor" "Antenna")
        (capacitorRadio1.Rows 0)
        (capacitorRadio1.ItemHelpText "Select  Capacitor" "Select Anntenna")
        (capacitorRadio1.ResourceHints "UserOverrideAttrs:AttachTop,TopOffset,BottomOffset,LeftOffset,RightOffset")
        (capacitorRadio1.SelectCBRegardless True)
        (capacitorUpdate.Label "Update")
        (capacitorUpdate.AttachLeft True)
        (capacitorUpdate.Resizeable True)
        (capacitorUpdate.TopOffset 0)
        (capacitorUpdate.BottomOffset 0)
        (capacitorUpdate.LeftOffset 0)
        (capacitorUpdate.RightOffset 0)
        (capacitorUpdate.Cursor "UI link cursor image")
        (capacitorUpdate.ResourceHints "UserOverrideAttrs:AttachLeft,TopOffset,BottomOffset,LeftOffset,RightOffset,AttachRight")
        (.AttachLeft True)
        (.AttachRight True)
        (.AttachTop True)
        (.TopOffset 16)
        (.BottomOffset 16)
        (.LeftOffset 10)
        (.RightOffset 10)
        (.ResourceHints "Template:OKCancelPreviewDialog.Content" "UserOverrideCols:100" "UserOverrideRows:11111000")
        (.AttachBottom True)
        (.Decorated 1)
        (.Rows 20)
        (.Columns 20)
        (.Layout
            (Grid
                (Rows 0 0 0 0 0 1 0 0)
                (Cols 0 0 0)
                PushButton1 PushButton2 PushButton3 PushButton4 PushButton5
                (Pos 7 1)
                (Size 2 1)
                capacitorRadio1
                (Pos 7 2)
                (Size 2 1)
                capacitorUpdate
            )
        )
    )
)
